Dev
supernyandev/3D-Renderer-From-Scratch pull request #1
Opened 2024-01-11 13:21 UTC by supernyandev

2024-01-12 16:41 UTC, DimaTrushin requested changes
- Обрати внимания, что я не повторяю комментарии в случае повторной ошибки. Так что я ожидаю, что ты поправишь похожие ошибки по аналогии.
- У тебя какая-то проблема с форматированием. Ты видимо забыл запустить clang-format. Сделай, а то прям глаза вытекают. 
- Еще у тебя питонячий стиль писать конструкторы. Не забывай, что надо пользоваться списком инициализации в плюсах.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/CMakeLists.txt
> +set_target_properties(${PROJECT_NAME} PROPERTIES OUTPUT_NAME "main.out")
Новая строка в конце каждого файла. На это ругается git, значит при клонировании твоей репы будет эта ругонь и у всех пользователей. Так не делай никогда.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/CMakeLists.txt
> +set_target_properties(${PROJECT_NAME} PROPERTIES OUTPUT_NAME "main.out")
Плохо делать расширение платформо зависимым. Потому что на windows например принято делать exe для исполняемых файлов.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/World.h
> +        Eigen::Quaterniond camera_rotation_;
Нахуя, а главное зачем? Зачем тебе кватернионы?

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/World.h
> +        Eigen::Quaterniond camera_rotation_;
Что за дичь? Почему у тебя камера отдельна и ее координаты отдельно и ее ориентация отдельно? Это как так? Тело отдельно, голова отдельно? Тут явно проблемы с инкапсюляцией.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/World.h
> +        Camera camera_;
И я так понимаю, ты предполагаешь, что у тебя камера только одна и она приколочена к миру?

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/World.h
> +        const std::vector<ObjectContainer> &GetObjects();
- Тебе скорее всего нужно лишь предоставлять begin и end для пробежки по объектам.
- Кроме того, метод должен быть const.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/World.h
> +        struct ObjectContainer {
пробел между функцией и объявлением класса, это читать не возможно.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/World.h
> +        const Eigen::Vector3d GetCameraPosition();
Зачем тут столько пробелов между методами класса?

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/World.cpp
> +        objects_.back().object = std::move(object);
Какого хуя? Почему не
```cpp
objects.push_back(std::move(object));
```
?? У тебя в строчке 8 лишний конструктор вызывается.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/World.cpp
> +        objects_.back().global_rotation_  = Eigen::AngleAxis<double>(0,Eigen::Vector3d::UnitX());
1)  У тебя явно проблемы с форматированием нет пробела после запятой, лишний пробле перед присваиванием. Ты не отформатировал файлы проекта с помощью clang-format.
2) Когда ты видишь код вида obj.subobj.subsubobj = some_value; Это ошибка проектирования. Это значит, что у тебя не достаточно выразительный интерфейс. Кроме того, если у тебя AnyObject является классом, то у него есть инвариант, а раз есть инвариант, то к его членам не должно быть прямого доступа. Это все противоречит идее инкапсюляции. Собственно имя с _ в конце тебе это подсказывает, что ты стучишься не туда куда можно.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/World.cpp
> +namespace renderer {
У тебя не единообразное оформление, где-то есть пробел между инклудами и неймспейсом, где-то нет. Примени автоформатирование.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/World.h
> +            Eigen::Vector3d global_coordinates = {0, 0, 0};
Магическая константа. Должно быть что-то вроде Origin; Заведи константу с именем или статическую функцию.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/World.h
> +        void AddObject(AnyObject object, Eigen::Vector3d);
1) Если первый аргумент содержит имя переменной, то и второй тоже должен.
2) Сделай в начале класса using Vector3d = Eigen::Vector3d; тогда не надо будет тут везде обращаться к этим типам вручную.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/World.h
> +        const Eigen::Vector3d GetCameraPosition();
Методы должны быть const.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Vertex.h
> +       Eigen::Vector3d normal;
Сделай в начале структуры using-ги.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.h
> +        Renderer(size_t width, size_t height);
Рендерер не должен зависить от разрешения экрана. Это деталь имплементации пиксельного экрана.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.h
> +        size_t width_;
Данные должны быть в конце класса! Не перемешивай их с методами.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.h
> +        void Draw();
Очень странный метод с сайд эффектами. Я бы ожидал метод, который возвращает пиксельный экран с готовой картинкой.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.h
> +        void DrawTriangle(const Triangle&,const World::ObjectContainer&);
1) Почему этот метод публичный? Выглядит как деталь имплементации.
2) Если подтягиваешь тип из другого класса, заводи юзинги в начале класса, чтобы не обращаться через двойное двоеточие.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.h
> +        Eigen::Matrix<RGB, Eigen::Dynamic, Eigen::Dynamic> screen_;
Зачем явно указывать Eigen::Dynamic? Это же значение по умолчанию.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.h
> +        size_t width_;
Зачем эти данные хранить тут, если это размеры screen_? Это же просто лишнее повторение данных.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +        height_ = height;
Что за питонячий стиль? Перенести в список инициализации.
```cpp
enderer::Renderer(size_t width, size_t height)
  : screen_(Matrix(height, width)),
    height_(height),
    width_(width) {}
```
Но вообще это странно, что ты тут указываешь разрешение экрана и хранишь лишние данные.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +
Убрать лишние вертикальные пробелы.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +            vertices[i] = owner_object.object.GetMesh().GetVertices()[current.points[i]];
Это ошибка дизайна. У тебя какая-то дикая жуткая последовательность обращений. Это значит твой объект не знает как общаться с внешним миром и разрешает ему копаться в своих кишках.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +        Eigen::Matrix4d transformation_matrix = Eigen::Matrix4d::Zero();
Поставить assert на указатель.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +        transformation_matrix.col(3).topLeftCorner<3, 1>() = owner.global_coordinates;
Вот это нарушение уровня абстракции. Потому что ты тут хочешь написать
```cpp
Matrix4d transformation = makeTransformationMatrix();
```

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +            temp.w() = 0;//because it is a direction
Вот это выглядит, как недостаточное количество классов или функций. Ты тут делаешь низкоуровневую работу, которую приходится комментировать. То есть у тебя явно есть отличие между векторами и точками. И ты делаешь какие-то конвертирования вручную.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Objects.h
> +        double &B() { return val.z(); }
Пиздец. Если уж ты делаешь структуру, то не надо делать аксессоры. Сделай struct и убери все методы. Либо закрой все данные и сделай нормальные методы чтения и записи с соблюдением инварианта.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Objects.h
> +        }
```cpp
template<typename T>
AnyObject(T&& object) : inner_(std::make_unique_<Inner<T>>(std::forward<T>(object))) {}
```

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Objects.h
> +        }
Это упадет на пустом объекте. Надо не так
```cpp
AnyObject(const AnyObject& other)
  : inner_((other.inner_ ? other.inner_->Clone(): nullptr)) {}
```
Во-первых, ты не смотрел материалы лекций моих. А во-вторых, не смотрел код моего стирающего типа. Посмотри хотя бы одно из них.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Objects.h
> +        }
Убрать этот метод. Этого метода быть не должно. У тебя есть конструктор по произвольному типу.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Objects.h
> +            return *this;
Не верная имплементация. Надо
```cpp
return *this = AnyObject(val);
```

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Objects.h
> +        AnyObject(AnyObject &&) = default;
Добавить noexcept

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Objects.h
> +        AnyObject &operator=(AnyObject &&) = default;
Добавить noexcept

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Objects.h
> +            virtual ~InnerBase() {}
= default;

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Objects.h
> +            }
Опять не так. Нужно сделать два конструктора
```cpp
Inner(const T& value) : value_(value) {}
Inner(T&& value) : value_(std::move(value)) {}
```

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Objects.h
> +            std::unique_ptr<T> value_;
Здесь не нужен unique_ptr, это линее хранение по указателю. Сделай
```cpp
T value_;
```

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Objects.h
> +        }
- Плохая имплементация. У тебя inner_ может быть пустым, тогда ты не можешь вернуть Mesh, это не корректная операция всегда. Потому тебе нужен метод проверки на непустоту. Но можно вместо нестабильного интерфейса объявить оператор стрелку доступа к интерфейсу.

- Вместо этого метода можно вернуть указатель на InnerBase, тогда не придется по десять раз пробрасывать одни и те же методы.
```cpp
const InnerBase* operator->() const {
  return inner_.get();
}
InnerBase* operator->() {
  return inner_.get();
}
```
Тогда любой метод из интерфейса InnerBase можно будет вызывать так
```cpp
AnyObject x;
x->GetMesh();
```

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Objects.h
> +        struct Inner : InnerBase {
сделай классом.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Mesh.h
> +        const std::vector<Triangle>& GetTriangles()const;
Лучше предоставить методы которые возвращают прокси объекты, у которых есть методы begin и end. Потому что ты хочешь просто итерироваться по этим контейнерам. Вряд ли тебе нужно знать, что там лежит именно вектор.

2024-01-12 16:41 UTC, DimaTrushin commented on 3DRenderer/Model/Camera.h
> +        double near_plane_distance_ = 1;
Не делай магические константы. Сделай constexpr статические константы с дефолтными значениями.

2024-01-19 18:26 UTC, DimaTrushin requested changes
Накидал еще немножечко хуев.

2024-01-19 18:26 UTC, DimaTrushin commented on 3DRenderer/Model/World.h
> +    class ObjectHolder : public AnyObject {
Нахуя, а главное зачем наследовать от AnyObject!? Это же стирающий тип! Ты вообще не должен никак от него наследоваться. Его плюс в том, что от него не надо наследовать. Это как std::function. Ты же не наследуешься от нее, чтобы туда что-то положить. Это какая-то мега глупость. Убрать.
Я кажется понял, что ты делаешь. Вопрос: почему это не переменная класса?

2024-01-19 18:26 UTC, DimaTrushin commented on 3DRenderer/Model/Objects.h
> +        virtual std::unique_ptr<InnerBase> Clone() const = 0;
Сделай этот метод приватным, чтобы его не могли вызывать по указателю на InnerBase.

2024-01-19 18:26 UTC, DimaTrushin commented on 3DRenderer/Model/World.h
> +    static Vector3d GetOrigin();
А точно надо это делать приватным и потом делать друзьями все холдеры?

2024-01-19 18:26 UTC, DimaTrushin commented on 3DRenderer/Model/World.cpp
> +    : AnyObject(std::forward<AnyObject>(obj)) {
Тут не работает std::forward. Точнее в нем нет смысла. Здесь AnyObject не чистый шаблон, потому это всегда rvalue reference. Потому тут можно просто std::move() навесить. Будет читаемее.

2024-01-19 18:26 UTC, DimaTrushin commented on 3DRenderer/Model/World.cpp
> +    objects_.back().SetAngle(Eigen::AngleAxis<double>(0, Eigen::Vector3d::UnitX()));
Почему эти данные не передаются при создании объекта в emplace_back? У тебя по хорошему вся эта хреноверть с ObjectHolder нужна для того, чтобы у тебя был объект помещенный в world. А для него не имеет смысла неиметь позиции и направления. А тогда вопрос, почему их не сообщаем в emplace_back при построении? Ты не создал достаточное количество правильных конструкторов для создания и потому у тебя тут идет цепной вызов кишков.

2024-01-19 18:26 UTC, DimaTrushin commented on 3DRenderer/Model/World.cpp
> +World::CameraHolder::CameraHolder(const Camera &cam) : Camera(cam) {
Если ты принимаешь камеру и складываешь ее внутри, то почему не принять ее by value и мувнуть в себя?

2024-01-19 18:26 UTC, DimaTrushin commented on 3DRenderer/Model/Utils.h
> +using Quaterniond = Eigen::Quaterniond;
Помести эти юзинги внутрь класса, где ты используешь. Не надо делать в случайном месте кода случайные глобальные юзинги.

2024-01-19 18:26 UTC, DimaTrushin commented on 3DRenderer/Model/Utils.h
> +    Direction& operator=(const Eigen::Product<T, F>& evaluable) {
Что за хуйня? Я все понимаю, но почему обязательно для типа Product?? Почему тогда не общий шаблон от T?

2024-01-19 18:26 UTC, DimaTrushin commented on 3DRenderer/Model/Utils.h
> +    Direction& operator=(const Vector4d&);
Вместо операторов присваивания лучше сделай конструкторы от них. Это эффективнее. И мув приваивание затригерится.

2024-01-19 18:26 UTC, DimaTrushin commented on 3DRenderer/Model/Utils.cpp
> +
зачем тут пустая строка?

2024-01-19 18:26 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.h
> +    Screen Draw(const World &world, size_t width, size_t height);
А ты отказался от идеи передавать Screen как параметры с уже выделенной памятью?

2024-01-19 18:26 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +Renderer::Renderer() {
Почему не Renderer() = default;?

2024-01-19 18:26 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +Screen Renderer::Draw(const World &world, size_t width, size_t height) {
Порядок методов в cpp файле должен быть точно такой же как в h файле!

2024-01-19 18:26 UTC, DimaTrushin commented on 3DRenderer/Model/Objects.h
> +        Inner(const std::remove_reference_t<T> &value) : value_(value) {
А что где-то пожаловалось на наличие ссылки?

2024-01-19 18:26 UTC, DimaTrushin commented on 3DRenderer/Model/Objects.h
> +        Inner(T &&value) : value_(std::forward<T>(value)) {
Здесь нужно std::move, потому что это не шаблонный конструктор.

2024-01-19 18:26 UTC, DimaTrushin commented on 3DRenderer/Model/Objects.h
> +class BasicObject {
Этот класс видимо вообще не нужен?

2024-01-19 18:26 UTC, DimaTrushin commented on 3DRenderer/Model/Objects.h
> +protected:
Нахрена данные защещенные, а не приватные?

2024-01-19 18:26 UTC, DimaTrushin commented on 3DRenderer/Model/Objects.h
> +class RGB {
Странно что эта структура тут делает. Это же хедер для стирающего типа.

2024-01-19 18:26 UTC, DimaTrushin commented on 3DRenderer/Model/Objects.h
> +class BasicObject {
Странно что эта структура тут делает. Это же хедер для стирающего типа.

2024-01-19 18:26 UTC, DimaTrushin commented on 3DRenderer/Model/Mesh.h
> +
Зачем столько вертикальных пустых строк?

2024-01-19 18:26 UTC, DimaTrushin commented on 3DRenderer/Model/Mesh.h
> +    Iterable<TrianglesConstIterator> GetTrianglesIterable() const;
1) То что у тебя Iterable это не значит, что название надо делать таким. Сделай GetTriangles() и все.
2) Заведи юзинг для возвращаемого значения.

2024-01-19 18:26 UTC, DimaTrushin commented on 3DRenderer/Model/Mesh.h
> +    using VerticesConstIterator = decltype(std::declval<const std::vector<Vertex>>().begin());
Что за ебанутый метод получать тип?

2024-01-19 18:33 UTC, supernyandev commented on 3DRenderer/Model/Objects.h
> +class BasicObject {
Нужен будет потом наверное, когда я объекты начну создавать

2024-01-19 18:35 UTC, supernyandev commented on 3DRenderer/Model/Mesh.h
> +    Iterable<TrianglesConstIterator> GetTrianglesIterable() const;
Зачем юзинг заводить, тут же всё лаконично и понятно

2024-01-20 13:26 UTC, supernyandev commented on 3DRenderer/Model/Mesh.h
> +    using VerticesConstIterator = decltype(std::declval<const std::vector<Vertex>>().begin());
А какой нормальный метод?

2024-01-20 15:08 UTC, supernyandev commented on 3DRenderer/Model/World.h
> +    class ObjectHolder : public AnyObject {
Что значит не переменная класса, у меня есть вектор object holder'ов

2024-03-26 13:28 UTC, DimaTrushin requested changes
Уф...
У тебя как попало разбросаны доступы к пространству имен.

Так же какая-то хрень с форматированием. Явно clang-format не применялся к файлам. Запускай его при сохранении файлов, а не в ручном режиме. Ты будешь забывать его запускать.

Плохая разбивка на компоненты. Я описал где-то в комментариях к Application в чем проблема.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Observer/Observer.h
> +    using CObservable1 = CObservable<CData, CSendBy>;
Можно назвать CMyObservable. А компилятор не дал возможности зашейдить имя?

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/CMakeLists.txt
> +add_custom_command(OUTPUT tags
Это очень некрасиво пользоваться кросплатформенными библиотеками и потом в системе сборке в наглую пользоваться линуксовыми командами без какой-либо попытки обернуть эту команду внутрь проверки какая операционная система. Как я по твоему это должен буду собирать на винде?

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Application.cpp
> +    model.Subscribe(view.GetRecievePort());
Плохой дизайн. У тебя все эти данные помрут после вызова метода run. С таким дизайном вообще не понятно зачем тебе иметь класс Application. По хорошему он как раз в своем конструкторе должен создать все объекты. То есть я бы ожидал
```cpp
class Application {
using Model = model::Model;
using View = view::View;
using Controller = controller::Controller;
public:
  Applicatoin();
  void run();
private:
  static constexpr int k_default_width_ = 1500;
  static constexpr int k_default_height_ = 1000;

  Model model_;
  View view_;
  Controller controller_;
};

Application::Application()
  : model_(k_default_width_, k_default_hight_),
    view_(k_default_width_, k_default_hight_),
    controller_(&model_) {
  model_.subscribe(view_.port());
  view_.subscribe(controller_.port());
}
```

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Application.cpp
> +    model::Model model(Application::GetWidth(), Application::GetHeight());
Максимально плохие пространства имен. Обрати внимание, что у тебя по сути имена дублируются. Нет никакого смысла в том, что Model лежит внутри model. Потому что внутри model явно не может лежать ни View, ни Controller. А если даже и лежит, то что такое model::View? А если ты захочешь создать еще одну модель, то куда ее положишь? Создашь пространство имен model2? А тогда надо будет менять везде пространство имен model на model1? И папки все поменять? В целом деление на пространства имен должно отражать архитектуру. Например принадлежность к ядру или интерфейсу. Я бы ожидал, что Model лежит внутри kernel. А View и Controller внутри interface. Это было бы логично. Но так же у тебя внутри ядра могут быть разные модели и одна модель может быть подписана на другую.
Кроме того, абстрактные имена Model, View и Controller плохо отражают назначение. Что это за Model у тебя? Назови ты его GraphicEngine и это будет твоя Model. Вместо View сделай более креативное название вроде MainScreen или что-то такое. Потому что ты вообще говоря можешь вывести на несколько окон свою картинку, это никто не запрещает делать. Кроме того и контроллер можно назвать GraphicEngineController или более кратко GEngineController, чтобы не печатать миллионы слов. Это хоть как-то скажет о предназначении твоих элементов. Ты должен помнить, что с каждым типом у тебя может быть много переменных такого типа. И  модели одного типа могут быть взаимозаменяемы. Потому конкретную роль отражает имя модели. Например View может быть как главным экраном или вспомогательным экраном или миникартой (например) или это вообще может быть консль или view для логирования в текстовый файл. Это может быть что угодно.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Application.cpp
> +    controller::Controller controller;
Странно что контроллер не присасывается к модели. Как он будет управлять моделью?

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Application.cpp
> +    while (true) {
Максимально близко как к правильному решению, так и к полному пиздецу. Что мешало сделать
```cpp
bool is_running= true;
while (is_running) {
  // implementation
}
```
???

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Application.cpp
> +            closed = controller.HandleEvent(event, model);
Так вот как ты сделал. Ну это ломает всю идею соединения контроллера с моделью. Я бы просто хранил указатель на модель внутри контроллера и тут бы просто скармливал контроллеру event и все. Ну и так как у тебя контроллер получает события не из view, то его НЕ надо подписывать на view.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Application.cpp
> +        }
А нельзя сразу внутри предыдущего while сделать return?

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Controller/Controller.cpp
> +bool Controller::HandleEvent(const sf::Event& event, model::Model& model) {
Старайся не передавать аргументы по неконстантной ссылке кроме тех ситуаций где без этого никак (как например оператор ввода operator>>, где это просто часть сигнатуры). Просто в коде
```cpp
controller.HandleEvent(event, model);
```
НЕ очевидно, что model поменяется. Потому лучше передавать такие аргументы по указателю
```cpp
controller.HandleEvent(event, &model);
```
Как в функции scanf. Тут & подсказывает, что model может поменяться. Но вообще идея контроллера напрямую ссылаться на модель. По-хорошему тут должно быть соединение похожее на observable-observer, но для простоты можно забить и просто указатель хранить и требовать этот указатель в конструкторе.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Controller/Controller.cpp
> +bool Controller::HandleKeyEvent(const sf::Event& event, model::Model& model) {
Так как ты обрабатываешь конкретное событие, а именно нажатие клавиши, то передавай сразу event.key сюда, а не весь event. Тогда тебе не придется писать груду кода в виде event.ket.code. Ты просто напишешь key.code. Это как раз и будет говорить о том, что эта функция правильно ставит границы взаимодействия, ей нужен только key из event и уже только она может лезть глубже внутрь.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Controller/Controller.h
> +    RecievePortType *GetRecievePort();
У тебя нет необходимости в этом методе. Так как у тебя контроллер напрямую получает события через метод HandleEvent.
И еще я удивлет если это компилируется, так как у тебя тут ошибка линковки, этот метод нигде не определен.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Controller/Controller.h
> +    bool HandleKeyEvent(const sf::Event &, model::Model &);
Этот метод должен быть приватным.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Controller/Controller.h
> +    using RecievePortType = observer::CObserver<std::shared_ptr<const renderer::Screen>>;
Нет необходимости в этом юзинге.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Controller/Controller.cpp
> +}
Вместо такого надо писать Controller() = default;

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/AnyObject.cpp
Убери пустые cpp файлы.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/AnyObject.h
> +    AnyObject(T &&object) : inner_(new Inner<std::remove_reference_t<T>>(std::forward<T>(object))) {
Что мешало сделать make_unique?

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/AnyObject.h
> +        : inner_(std::make_unique<Inner<std::remove_reference_t<T>>>(object)) {
Убрать, этот шаблон повторяет предыдущий. Дело в том, что когда у тебя шабло нимеет вид
```cpp
template<typename T>
AnyObject(T&& object);
```
То T&& биндится и на lvalue reference и на rvalue reference. Именно для этого и нужен std::forward, потому что ты не знаешь на что именно забиндился аргумент и не можешь просто вызвать std::move.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/AnyObject.h
>          }
В этом случае у тебя не шаблонный конструктор и T&& это только rvalue reference. Тут бы хорошо вместо forward сделать более явный move (хотя оказывается и с forward это должно работать).

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Application.cpp
> +        while (view.GetEvent(event)) {
Плохой дизайн. Плохо, что view у тебя отвечает за обработку сообщений. Этот дизайн наследуется из sfml напрямую. Потому что у них sfml::window это и обработчик event loop-а и view объект одновременно. И так как оно у них слеплено воедино, то тебе тяжело разделить их.
Мне сложно сказать сходу как это пофиксить по-хорошему. Хотелось бы, чтобы Application крутил event loop (или точнее run-time loop, потому что тут у тебя busy waiting), но при этом view тогда оповещал controller напрямую через observer pattern. Это большой вопрос на подумать...

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/View/View.h
> +    bool GetEvent(sf::Event &event);
Вот этот метод -- это то, что меня напрягает сильно. Но это к сожалению дизайн sfml и тяжело что-то с этим поделать. Я в Application.cpp написал про это более подробно.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/View/View.h
> +    using RecievePortType = observer::CObserver<std::shared_ptr<const renderer::Screen>>;
Вот какой вопрос. У тебя обзервер блокирующий. Нужно ли заморачиваться с shared_ptr? То есть при отрисовке во view, ты все равно копируешь данные из экрана. Потому нет смысла в таком сложном объекте для передачи данных. Просто передавай по ссылке Screen и копируй из него данные в методе Draw как и сейчас. И все.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/View/View.h
> +    };
Странно, что это внутри View определяется. Это что-то более глобальное.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/View/View.h
> +    using MatrixXRGBA = Eigen::Matrix<RGBA, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor>;
Вот это я бы вынес отдельно в отдельный хедер.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/View/View.h
> +    RecievePortType recieve_port_;
добавь пробел между 21 и 22 строчкой, чтобы отделить методы от данных.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/View/View.cpp
> +    MatrixXRGBA matrix = Make8BitRgbMatrix(screen->GetScreenMatrix());
Вот тут ты копируешь данные из экрана в матрицу цветов. Потом в строчке 23 ты судя по всему опять копируешь данные, но уже из матрицы цветов в sf::Image. И потом в строчке 26 ты копируешь эти данные внутрь sf::Texture. Как минимум этого копирования в строчке 21 можно избежать.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/View/View.cpp
> +                 reinterpret_cast<const uint8_t *>(matrix.data()));
Во-первых, почему размеры берутся от screen, а данные из matrix? Во-вторых, зачем вообще нужен был matrix? Почему нельзя было напрямубю из screen копировать данные? В-третьих, reinterpret_cast означает, что ты не продумал интерфейсы для правильного взаимодействия. Тут должна быть вызвана вспомогательная функция что-то вроде createImage( const Screen&); которая возвращает sf::Image.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/View/View.cpp
> +    sprite.setTexture(render_texture_);
Удивительно витееватый метод отрисовки на экране... Любопытно, а что можно установить несколько текстур на спрайт? или можно загрузить несколько изображений в текстуру? В чем смысл?

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/View/View.cpp
> +    ans.R = std::max(static_cast<uint8_t>(color.GetR() * 255.0), uint8_t{0});
Сделай методы у RGB которые возвращают значения нужного типа, и не делай тут явные касты. Это и сократит количество кода и сделает его более читаемым. Например ты можешь сделать метод getRf и getRi для double и integer.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/View/View.cpp
> +    ans.A = 255;
Это магическая константа. Лучше заведи псевдоним Opaque (непрозрачный) и Transparent (прозрачный) для крайних значений. А еще можешь сделать это поле дефолтным.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/View/View.cpp
> +View::RGBA View::DRGBTo8BitRGBA(const renderer::RGB &color) {
Тут явно у тебя есть два типа RGB и RBGA и ты пытаешься по второму построить первый. Я не понимаю, почему это не занимает одну строчку?
```cpp
RGB x;
RGBA y = x;
```
?? Для этого лишьт надо сделать метод преобразования одного типа к другому. Либо сделать статический метод либо глобальную функцию вида
```cpp
RGB x;
RGBA y = RGBA::fromRGB(x);
```

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/View/View.cpp
> +    : recieve_port_([](std::shared_ptr<const renderer::Screen>) {},
для этого есть специальный статический метод в обзервере doNothing

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.h
> +    friend class model::Model;
НАХУЯ, БЛЯТЬ, НАХУЯ!?? Убрать эту поебень! Это даже не ошибка дизайна, это просто плевок всему объектно ориентированному программированию в рожу. Нахуя тебе классы и  инкапсюляция, когда совершенно случайный класс, который вообще не должен ничего общего иметь с Renderer имеет право полного доступа к его внутренностям? Убрать и сделать у Renderer-а нормальный публичный интерфейс которым можно пользоваться без вот этого говна. Нет у модели и рендерера совместных инвариантов, чтобы шарить в отличие от observer и observable.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.h
> +    const Eigen::Matrix<double, 5, 4> kPlanes{
Почему блять не static? Не делай константные поля в классе.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +        min_x = std::min(static_cast<size_t>(std::floor(screen_triangle.row(i).x())), min_x);
Выглядит так что у тебя есть непрерывные и дискретные координаты на плоскости и тут тебе не хватает функций перевода из одних координат в другие и потому ты тут пользуешься кастами и округлениями явно.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +    assert("bounded dimensions are OK" && max_x < screen->GetWidth() &&
Это сообщение появится когда assert сработает. Потому тут лучше писать предупреждение, что не так пошло.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +            Eigen::Vector2d vec = {static_cast<double>(x) + 0.5, static_cast<double>(y) + 0.5};
Опять выглядит как нехватка преобразований координат в другую сторону.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +            if (CheckIfInside(b_coordinate)) {
Мне не нравится 4 вложенных scope. Даже в ядре Linux запрещено иметь больше 3.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +    Triangle vertices = owner_object->GetMesh().GetTriangleVertices(current);
1) Мне немного плохо от количества уровней доступа obj->method().method(arg).
2) Странно, что Mesh имеет только один треугольник или я что-то не понимаю.
3) Это нормально, что ты делаешь копию треугольника тут?

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +
А где клиппинг? Отрезание невидимых частей треугольника по пирамиде? Его надо сделать до преобразования в куб, потому что проективное преобразование может порвать треугольник.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +        ClipAllTriangles(kPlanes.row(i), &triangles);
Если это уже в координатах единичного куба, то у тебя могли быть некорректные треугольники. Если например часть вершин треугольника видима и в пирамиде, а одна вершина сзади нас за камерой.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +    std::list<Eigen::Matrix3d> triangles;
Почему list?

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +    Renderer::ApplyHomogeneousTransformationMatrix(transformation_matrix, vertices);
А почему такое длинное название? Почему нельзя просто назвать метод apply? Ведь в плюсах есть перегрузка операторов и тип того, что ты применяешь определяется и будет стаять в первом аргументе.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +        world.GetCameraRotation().inverse(), -world.GetCameraPosition());
Выглядит странно, когда ты методу скармливаешь не какой-то объект, а часть его частей. Такое ощущение, что ты не знаешь что у тебя метод должен принимать.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +    Renderer::ApplyHomogeneousTransformationMatrix(transformation_matrix, &(*vertices));
зачем &*? Для читаемости?

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +std::unique_ptr<Screen> Renderer::Draw(const World &world, size_t width, size_t height) {
добавь пустую строку между неймспейсом и следующей функцией. И убери ; после неймспейса оно не надо.э

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +    double dheight = static_cast<double>(height);
не нравятся мне касты...

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +Eigen::Matrix3d TransformToScreenSpace(Eigen::Matrix3d triangle, size_t width, size_t height) {
Значит для Vector3d ты сделал using, а для Eigen::Matrix3d нет. Будь единообразным. Сделай для всего юзинги.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +Vector3d ConvertToBarycentric(Eigen::Vector2d coordinates, const Eigen::Matrix3d &triangle) {
Убери явно все квалификаторы доступа к Eigen. Ты же заводил юзинги, почему тут не используешь?

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Primitives.h
> +class BarycentricCoordinateSystem {
Название явно врет.У тебя хранится треугольник внутри. Потому это НЕ система координат, это явно что-то другое. Измени название на более подходящее.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Primitives.h
> +    Matrix2d barycentric_transformation_matrix_;
Выглядит как куча лишних зависимых данных. Для любой линейной системы координат достаточно указать точку начала и базисные точки для разложения. У тебя тут явно хранится на порядок больше данных.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Primitives.h
> +    Triangle original_;
А это что делает в системе координат? Это тогда треугольник с дополнительной информацией. Что это за хрень?

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Primitives.h
> +    Eigen::Vector3<BCoordinates> GetTriangle();
1) Какого хуя у тебя тут используется Eigen? Почему не сделал юзинг?
2) Почему метод не константный и при этом называется Get?
3) Почему возвращает по значению, а не по ссылке и называется Get, а не Make или Create?

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Primitives.h
> +    Eigen::Vector3<Vector3d> GetTransformedTriangleCoordinates(
Что мешало вернуть матрицу?

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Primitives.h
> +    Eigen::Matrix<double, 3, 4> GetVerticesHomogeniousCoordinates() const;
Зачем тебе юзинги если ты их то используешь, то нет?

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Primitives.h
> +    // bad design :-)
К чему относится этот комментарий? К строчке выше или ниже? В чем проблема?

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Primitives.cpp
> +    verticies_.x().coordinates = static_cast<Eigen::Vector3d>(coordinates.row(0));
Судя по всему ты нагородил лишних типов и теперь тебе приходится кастовать их друг к другу. Очень здорово. Почему не использовать только вектора и матрицы из Eigen?

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Primitives.cpp
> +    verticies_.x().coordinates = static_cast<Eigen::Vector3d>(coordinates.row(0));
Питонячий стиль. Вся инициализация должна быть в списке инициализации.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Object.h
> +    BasicObject(const BasicObject &) = default;
Какого хуя? Убрать это говно нахуй. Ты ломаешь move семантику и потенциально можешь сделать ub таким кодом.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Object.h
> +    void AddTriangle(const Eigen::Matrix3d &);
Заведи что ли единый файл с глобальными юзингами и используй их везде, а то у тебя пространства имен как попало используются.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Object.cpp
> +void renderer::BasicObject::AddTriangle(const Eigen::Matrix3d& coordinates) {
Я так понимаю эта матрица имеет тяжелую локальную часть.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Model.h
> +    std::optional<std::shared_ptr<const renderer::Screen>> GetCurrentScreen();
Optional от любого поинтера -- это пиздос. У него же есть состояние nullptr!

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Model.h
> +    renderer::Renderer renderer_;
заведи юзинги в начале класса, чтобы не стучаться через миллионы пространств имен

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Model.h
> +    int height_;
Эти данные вроде как в экране лежат.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Model.h
> +    std::shared_ptr<const renderer::Screen> current_screen_;
А тебе нужно хранить тут экран дополнительно?

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Model.cpp
> +namespace model {
добавь пробел между инклудами и пространством имен

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Model.cpp
> +      update_port_([this]() { return GetCurrentScreen(); }),
что мешало просто сделать return current_screen_?

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Model.cpp
> +      update_port_([this]() { return GetCurrentScreen(); }),
Данные в списке инициализации ДОЛЖНЫ БЫТЬ в том же порядке, в каком они объявлены в классе! Добавь это в warning-ги компилятора.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Model.cpp
> +void Model::Subscribe(observer::CObserver<std::shared_ptr<const renderer::Screen>>* obs) {
И нахуя тебе был нужен псевдоним для этого типа?

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Model.cpp
> +    current_screen_.reset(screen.release());
что мешало написать 
```cpp
current_screen_ = std::move(screen);
```
??

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Model.cpp
> +    std::unique_ptr<renderer::Screen> screen(std::move(renderer_.Draw(world_, width_, height_)));
тут лишнее std::move.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Screen.h
> +    Screen(const Screen &) = default;
Убрать, убрать нахуй.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Screen.h
> +    const RGB &GetPixel(size_t row, size_t column) const;
У тебя то size_t то int используется для размеров. А Eigen использует  Eigen::Index. Нужно единообразие.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Screen.cpp
> +renderer::Screen::Screen(size_t width, size_t height) : screen_matrix_(height, width) {
Открой namespace и не пиши через квалификатор
```cpp
namespace renderer {
// весь код тут
}
```

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Utils.h
> +    RGB(const std::initializer_list<double> &);
initializer_list надо принимать by value, потому что он уже указатель внутри и его дешево копировать, а по ссылке или указателю это лишний прыжок по памяти. Ну и не идеоматично.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Camera.cpp
> +Camera::Camera(int width, int height) {
Порядок методов в cpp файле должен быть точно такой же как в h файле!

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Camera.cpp
> +    t_ = -b_;
Нарушение уровня абстракции. У тебя тут идет низкоуровневая возня, а потом внезапно вызов функции.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Camera.cpp
> +    ;
Это что еще за хуйня?

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Camera.h
> +    void InitPerspective();
Лучше оформлять статические методы по построению объектов так
```cpp
static Matrix4d createPerspective(...);
```
и использовать их в списке инициализации.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Camera.h
> +    Camera(int width, int height);
Если что в Eigen тип размера Eigen::Index.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Camera.h
> +#include <array>
У тебя не консистентно оформлены хедеры.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Mesh.cpp
> +Triangle Mesh::GetTriangleVertices(const ITriangle& triangle) const {
Если метод строит что-то, то лучше называть его make или create, чтобы пользователь метода не думал, что он получает доступ по ссылке к внутренним данным и знал, что это дорогое удовольствие.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Utils.cpp
> +        if (it == triangles->begin()) {
что мешало сделать do {} while();?

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Utils.cpp
> +                break;
опять 4 scope

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Utils.h
> +    }
А это зачем? Почему нельзя явно вызывать eval там где ты хочешь подавить ленивые вычисления? Причем это сработает на любой тип, даже если  нет eval и тогда будет просто ошибка компиляции.

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Utils.h
> +void ClipAllTriangles(const Eigen::Vector4d &plane, std::list<Eigen::Matrix3d> *triangles);
Почему это не методы рендерера?

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/Vertex.h
> +    Vertex() = default;
Нахуя тебе конструктор для структуры?

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/World.h
> +
Это что за фестиваль пустых строчек?

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/World.cpp
> +    objects_.back().SetAngle(Eigen::AngleAxis<double>(0, Eigen::Vector3d::UnitX()));
Почему нельзя было эти данные передать в конструкторе в emplace?

2024-03-26 13:28 UTC, DimaTrushin commented on 3DRenderer/Model/World.cpp
> +World::CameraHolder::CameraHolder(Camera camera) : Camera(std::move(camera)) {
Камера у тебя структура с тяжелой локальной частью, для нее нет разницы между мувом и копированием. Надо следить за такими объектами. Заведи себе это в качестве привычки. Для таких объектов надо передавать данные по ссылкам.

2024-03-26 13:40 UTC, supernyandev commented on 3DRenderer/Model/Renderer.h
> +    const Eigen::Matrix<double, 5, 4> kPlanes{
я пробовал static, никак не получается

2024-03-26 17:01 UTC, supernyandev commented on 3DRenderer/Model/Model.cpp
> +      update_port_([this]() { return GetCurrentScreen(); }),
Нету такого ворнинга же

2024-04-04 13:05 UTC, supernyandev commented on 3DRenderer/Application.cpp
> +        while (view.GetEvent(event)) {
так то тут ждется появления ивента, поэтому это не busy waiting

2024-04-04 15:26 UTC, vvminashkin commented on 3DRenderer/View/View.h
> +    };
это структура для реализации, наверное нужно в cpp

2024-04-04 15:28 UTC, supernyandev commented on 3DRenderer/View/View.h
> +    using MatrixXRGBA = Eigen::Matrix<RGBA, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor>;
зачем..

2024-04-04 15:30 UTC, supernyandev commented on 3DRenderer/View/View.cpp
> +    MatrixXRGBA matrix = Make8BitRgbMatrix(screen->GetScreenMatrix());
Эм нет, не копирую а конвертирую

2024-04-04 15:32 UTC, supernyandev commented on 3DRenderer/View/View.cpp
> +                 reinterpret_cast<const uint8_t *>(matrix.data()));
в screen они хранятся как даблы.

2024-04-04 15:33 UTC, supernyandev commented on 3DRenderer/View/View.cpp
> +    sprite.setTexture(render_texture_);
так sfml требует

2024-04-09 11:15 UTC, supernyandev commented on 3DRenderer/Model/Renderer.cpp
> +            Eigen::Vector2d vec = {static_cast<double>(x) + 0.5, static_cast<double>(y) + 0.5};
не, это центрирование

2024-04-09 11:16 UTC, supernyandev commented on 3DRenderer/Model/Renderer.cpp
> +            if (CheckIfInside(b_coordinate)) {
ну, это из-за геометрии

2024-04-09 11:19 UTC, supernyandev commented on 3DRenderer/Model/Renderer.cpp
> +    Triangle vertices = owner_object->GetMesh().GetTriangleVertices(current);
1. да
2. получаю треугольник по его номерам 
3. да

2024-04-09 11:45 UTC, supernyandev commented on 3DRenderer/Model/Renderer.cpp
> +    std::list<Eigen::Matrix3d> triangles;
алгоритм клипинга

2024-04-09 15:00 UTC, vvminashkin commented on 3DRenderer/Model/Primitives.h
> +class BarycentricCoordinateSystem {
а что это тогда..

2024-04-09 15:28 UTC, supernyandev commented on 3DRenderer/Model/Primitives.cpp
> +    verticies_.x().coordinates = static_cast<Eigen::Vector3d>(coordinates.row(0));
не получается по-другому

2024-04-09 15:41 UTC, supernyandev commented on 3DRenderer/Model/Screen.h
> +    Screen(const Screen &) = default;
???

2024-04-09 16:03 UTC, vvminashkin commented on 3DRenderer/Model/Camera.h
> +    void InitPerspective();
так не получится, мне надо всё до инициализировать

2024-05-20 08:27 UTC, DimaTrushin requested changes
сделал случайные замечания.

2024-05-20 08:27 UTC, DimaTrushin commented on 3DRenderer/Application.cpp
> +    controller_.InitEnviroment();
Что это за хуйня? Почему контроллер не выполняет всю инициализацию в своем конструкторе? Конструкторы ровно для этого и нужны, чтобы инициализировать объекты. Если у тебя есть метод с названием init, это всегда ошибка дизайна.

2024-05-20 08:27 UTC, DimaTrushin commented on 3DRenderer/Application.cpp
> +        if (view_.GetEvent(event)) {
Ну вот в smfl к сожалению у них их window это сплав всего вместе. Это и view и controller и model в одном флаконе и еще и runtime. Потому приходится писать такое говно.

2024-05-20 08:27 UTC, DimaTrushin commented on 3DRenderer/CMakeLists.txt
> +#set_source_files_properties(tags PROPERTIES GENERATED true)
Не оставляй комментарии с кодом.

2024-05-20 08:27 UTC, DimaTrushin commented on 3DRenderer/Application.cpp
> +void HandleException() {
Порядок методов в cpp файле должен быть точно такой же как в h файле!

2024-05-20 08:27 UTC, DimaTrushin commented on 3DRenderer/Controller/GEngineController.h
> +    static constexpr double kDefaultMove = 0.1;
Стоит добавить вертикальный пробел между статическими данными и данными класса.

2024-05-20 08:27 UTC, DimaTrushin commented on 3DRenderer/Controller/GEngineController.h
> +    void HandleKeys();
стоит добавить вертикальный пробел между приватными методами и статическими данными.

2024-05-20 08:27 UTC, DimaTrushin commented on 3DRenderer/Controller/GEngineController.h
> +    bool HandleKeyPressedEvent(const sf::Event::KeyEvent&);
Добавь using-ги чтобы не писать такие длинные квалификаторы доступа.

2024-05-20 08:27 UTC, DimaTrushin commented on 3DRenderer/Controller/GEngineController.h
> +    void InitEnviroment();
По названию эта функция должна быть частью конструктора. Нахуя ты ее сюда добавил?

2024-05-20 08:27 UTC, DimaTrushin commented on 3DRenderer/Controller/GEngineController.h
> +namespace interface {
сделай пробел между include директивами и перым пространством имен. Вообще выглядит так как будто ты не применяешь clang-format. Настрой свою IDE так, чтобы она применяла его на сохранении файлов.

2024-05-20 08:27 UTC, DimaTrushin commented on 3DRenderer/Controller/GEngineController.cpp
> +void GEngineController::InitEnviroment() {
Так вот что это такое... Ну это делается не так. Ты смешал все в кучу. Ты не верно понял MVC, у него НЕ должно быть ТОЛЬКО 3 объекта. Эти три объекта это лишь один контур. MVC используется на малом масштабе. То есть если ты хочешь сделать инициализацию сцены из консоли, то по хорошему у тебя должна быть view для консольного вывода и контроллер для консоли и модель для состояния логики управления из консоли. НЕ надо пихать все в один контроллер.

2024-05-20 08:27 UTC, DimaTrushin commented on 3DRenderer/Controller/GEngineController.cpp
> +}
Где вертикальные пробелы между функциями в cpp файле?

2024-05-20 08:27 UTC, DimaTrushin commented on 3DRenderer/View/MainScreen.h
> +#include "../Observer/Observer.h"
У тебя не отсортированы хедеры.

2024-05-20 08:27 UTC, DimaTrushin commented on 3DRenderer/View/MainScreen.cpp
> +          RecievePortType::doNothing, [this](const renderer::Screen& screen) { Draw(screen); },
Какого хрена ты отключил действия на подписку? Это прямое наружение задачи view. Она должна отражать состояние модели в любом момент времени, в том числе в момент подписки. Так тебе потребуется дополнительная синхронизация.

2024-05-20 08:27 UTC, DimaTrushin commented on 3DRenderer/View/MainScreen.cpp
> +          RecievePortType::doNothing, [this](const renderer::Screen& screen) { Draw(screen); },
Почему не сделан using для Screen?

2024-05-20 08:27 UTC, DimaTrushin commented on 3DRenderer/View/MainScreen.cpp
> +      window_(sf::VideoMode(width, height), "renderer") {
по-хорошему "rednerer" это тоже магическая константа.

2024-05-20 08:27 UTC, DimaTrushin commented on 3DRenderer/View/MainScreen.cpp
> +
Ты не консистентен. У тебя то есть то нет вертикальных пробелов.

2024-05-20 08:27 UTC, DimaTrushin commented on 3DRenderer/View/MainScreen.cpp
> +sf::Image MainScreen::MakeImage(const renderer::Screen& screen) {
Это делается для того, чтобы отвязать Screen от типа данных в sfml?

2024-05-20 08:27 UTC, DimaTrushin commented on 3DRenderer/View/MainScreen.cpp
> +sf::Image MainScreen::MakeImage(const renderer::Screen& screen) {
Почему этот метод НЕ статический или НЕ константный?

2024-05-20 08:27 UTC, DimaTrushin commented on 3DRenderer/Model/Utils.h
> +    // r,g,b
А почему тут альфа канал не используется?

2024-05-20 08:27 UTC, DimaTrushin commented on 3DRenderer/Model/Screen.h
> +    Screen &operator=(Screen &&) noexcept = default;
Зачем это тут? Если они дефолтные, то их НЕ надо писать. Потому что их компилятор за тебя сгенерирует и они будут считаться объявленными компилятором, а не тобой. А это всегда лучше.

2024-05-20 08:27 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.h
> +    std::unique_ptr<Screen> Draw(const World &world, size_t width, size_t height);
А накой черт тут uniqut_ptr?

2024-05-20 08:27 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +    std::unique_ptr<Screen> screen(new Screen(width, height));
Не используй new в коде

2024-05-20 08:27 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +void Renderer::RasterizeTriangle(const BarycentricCoordinateSystem &system,
Я бы выделил  растеризатор отдельно, чтобы не раздувать обязанности рендерера.

2024-05-20 08:27 UTC, DimaTrushin commented on 3DRenderer/Model/Renderer.cpp
> +    max_x = std::min(static_cast<size_t>(screen->GetWidth() - 1), max_x);
опять касты в бизнес логике.

2024-05-20 08:27 UTC, DimaTrushin commented on 3DRenderer/Model/AnyHolderPointer.h
> +        using MeshConstIterator = std::vector<Mesh>::const_iterator;
Зачем это тут?

2024-10-30 14:42 UTC, merged